Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.33.15"
  config.vm.synced_folder "../packages/", "/home/vagrant/ncs-run/packages"
  config.vm.provision "shell", inline: <<-SHELL
	 sudo apt-get -y update
	 sudo apt-get -y upgrade
	 mkdir /home/vagrant/project
   SHELL
end